version: '3.9'

services:
  cleanarchitecture.webapi:
    image: ${DOCKER_REGISTRY-}cleanarchitecturewebapi
    build:
      context: ../Source/
      dockerfile: ../Source/Src/Presentation/CleanArchitecture.WebApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=${ENVIRONMENT}
      - ConnectionStrings__DefaultConnection=Data Source=/app/App_Data/CleanArchitecture.db
      - ConnectionStrings__IdentityConnection=Data Source=/app/App_Data/CleanArchitectureIdentity.db
    ports:
      - "8080:8080"
    volumes:
      - appdata:/app/App_Data
    restart: unless-stopped

volumes:
  appdata:
    external: true
